### ISSUE TITLE
how to embed in a c#/f# peoject?

### ISSUE THREAD

**Issue by sep2** [metacall/core#167]
## 📚 Documentation

The readme said there is a port in c# which we can use to embed metacall, I assume it is a nuget package, but could not find the related docs/repo.

btw on the use case I am building an online game server that allows players to upload their plugin scripts to extend the game logic.

**Comment by viferga** [comment]
The C# Loader and Port has been a bit discontinued and it was one of the first ones that was implemented. It works but needs improvement ( https://github.com/metacall/core/issues/123 ). Right now there is a Port for it, but it is not published in NuGet: https://github.com/metacall/core/tree/develop/source/ports/cs_port/source

It may need to update the project because it was coded for NetCore 1.0, when it was in experimental version. The Loader has been updated to version 5 (although it has still some minor problems) but the Port has remained untouched.

Is this enough for you? Do you need documentation? Please feel free to ask for anything you need.

Right now C# only supports static methods from classes, and they are treated as functions (instead of fully supporting classes). But I think this should be enough for your use case, at the end you will need a static method for your scripts as an entry point, and this is exactly what it's supported.

If you are interested in contributing in order to improve the MetaCall C# support it would be great. I am not very skilled in C# and there's a lot of work in other parts to be done right now.

I hope this helps.

**Comment by sep2** [comment]
Thank you for the reply, that clear a lot!
