### ISSUE TITLE
Support TypeScript `Promise`s when embedding TypeScript into Golang

### ISSUE THREAD

**Issue by rojserbest** [metacall/core#174]
Parra
> we need to run all metacall calls  (any call to the API) in the same OS thread

Parra
> and also a fast way to dispatch those calls, but that's secondary

Parra
> this can be achieved with an internal event loop, running in a separated thread

Parra
> or by using the trampoline magic

Roman Sharkov
> just run a goroutine, make it call `runtime.LockOSThread()` and make it listen on a channel. Send everything you want this goroutine to do over this channel.

Roman Sharkov
> sounds pretty straightforward.. 
> 
> `type Work interface{}`
> `c := make(chan Work)`
>
> `go func(<-chan Work) {`
> `  runtime.LockOSThread()`
> `  for w := range c {`
> `    // do your single-threaded logic`
> `  }`
> `}(c)`

Also read [this](https://t.me/c/1307086795/25100) until [this](https://t.me/c/1307086795/25128) in [here](https://t.me/joinchat/BMSVbBatp0Vi4s5l4VgUgg).

**Comment by viferga** [comment]
Just for clarifying, what we are talking here is in order to enable go-routines with MetaCall Go Port. Basically it needs some kind of event loop and a way to dispatch fast the calls.

In other hand, there's the requirement of @rojserbest for implementing promises and callbacks so we can do more magic with the Go Port. Both things are related because probably Go will suffer if the callbacks or promises are executed in the wrong thread, so it should be reviewed in order to make production ready the Go Port.

**Comment by viferga** [comment]
Promise is not implemented yet, but `Await` has been already implemented and the Go Port is completely thread safe now, so I thing this issue can be closed:
https://github.com/metacall/core/commit/929faa1e78ec19c66b908753bd76896e07e39cd5
