### ISSUE TITLE
Any plans to support embedding Deno?

### ISSUE THREAD

**Issue by mweichert** [metacall/core#193]
Hi there,

Just a quick question. Are there any plans for adding support for embedding Deno? I see that you have an example for embedding NodeJS, but I'd love to use Deno given that it supports TypeScript out-of-the-box.

Thanks,
Mike

**Comment by viferga** [comment]
Hi @mweichert, we have a proof of concept for embedding Deno. But right now it involves modifying the code of Deno, because it does not have embedding API. It is very similar to what happened when embedding NodeJS (starting from version 8, it did not have embedding API until version 16). Not having embedding API implies a lot of pain or modifying the Deno source (which is something we try to avoid because it is very costly to maintain those modifications over time).

You can find the PoC of the `deno_loader` here: https://github.com/metacall/core/tree/develop/source/loaders/deno_loader

If you want to continue with the implementation, it would be great.

On the other hand, you can use our `ts_loader` which is based on `node_loader`. Basically it offers TypeScript (including TSX) based on NodeJS runtime instead of Deno. Maybe it can fit your use case.

If you want to keep talking about this in detail, please join one of our chats:
<div id="badges" align="center">
  <a href="https://t.me/joinchat/BMSVbBatp0Vi4s5l4VgUgg" alt="Discord">
    <img src="https://img.shields.io/static/v1?label=metacall&message=join&color=blue&logo=telegram&style=flat" /></a>

  <a href="https://discord.gg/upwP4mwJWa" alt="Discord">
    <img src="https://img.shields.io/discord/781987805974757426?label=discord&style=flat" /></a>

  <a href="https://matrix.to/#/#metacall:matrix.org" alt="Matrix">
    <img src="https://img.shields.io/matrix/metacall:matrix.org?label=matrix&style=flat" /></a>
</div>
