### ISSUE TITLE
Integrate Hadolint to lint Dockerfiles

### ISSUE THREAD

**Issue by padmajabhol** [metacall/core#224]
## 🚀 Feature

Hadolint is a docker file linter 

### Describe the solution you'd like
Integrate CI pipelines to configure hadolint with dockerfiles.

**Comment by viferga** [comment]
I am not sure if linter with Docker should be interesting, maybe it's better to implement some kind of tool for linting the scripts (everything under the `./tool/*` folder). The dockerfiles are usually small and they do not have a lot of code to lint.

Same for CMake files but the tooling is more complex.

For now I am closing the issue because it is not a priority.
