### ISSUE TITLE
Failed to compile Metacall with the Python loader because of conflicting types

### ISSUE THREAD

**Issue by devraymondsh** [metacall/core#414]
## 🐛 Bug Report
Compilation failure for the Python loader

### Expected Behavior
To compile

### Current Behavior
Doesn't compile, throws error about conflicting types

### Steps to Reproduce
Just compile with the Python loader option turned on

### [logs.txt](https://github.com/metacall/core/files/11139775/logs.txt)

**Comment by viferga** [comment]
You are compiling with Python 2, or for some reason it is finding Python 2 headers / lib instead of Python 3. This is not a code bug, you are configuring it wrong. For more info about proper configuration, check out the CI workflows if needed or open a new issue with more information about how you are setting up the dependencies and CMake.
