### ISSUE TITLE
unable to deploy once have package.json

### ISSUE THREAD

**Issue by durgesh077** [metacall/core#453]
### Steps to Reproduce

1.
2.
3.
4.

**Comment by durgesh077** [comment]
[useFuse.zip](https://github.com/metacall/core/files/12016700/useFuse.zip)

**Comment by Vaibhav0810** [comment]
Can you provide detail about what issue you are facing

**Comment by viferga** [comment]
@durgesh077 I have tested this on the MetaCall server from the FaaS and it works, so probably the bug is in the dashboard, later on I will try it on the FaaS directly to see what happens.

@Vaibhav0810 thanks for answering, but I told @durgesh077 to upload here this package that apparently failed on the FaaS. By the way, you are right. @durgesh077 you uploaded this by drag & drop the package or via metacall-deploy..? Or you used `metacall-gpt`? It would be cool to have some info because I am not sure how to reproduce it, the package looks pretty normal.

**Comment by durgesh077** [comment]
@viferga we fixed it on google meet

**Comment by viferga** [comment]
True, I forgot it xD

Thanks @durgesh077
