### ISSUE TITLE
Refactor Python loader code

### ISSUE THREAD

**Issue by Encrylize** [metacall/core#94]
I am currently reading through the code for the Python loader and have found a few recurring patterns that I believe could be improved:

1. A lot of the error handling cleanup code is quite repetitive and the current structure is quite error-prone. This could be improved by using `goto` to localize the cleanup code (see [this link](https://stackoverflow.com/questions/788903/valid-use-of-goto-for-error-management-in-c) for an example).
2. Variables are often declared at the start of scopes (i.e. C89 style), rather than when they are actually initialized. This makes it harder to reason about their scope and could be improved by only declaring the variables when they are to be initialized, thus making their scope as tight as possible.

If you agree with these observations, I will start working on implementing them in the codebase. Please see [this commit](https://github.com/Encrylize/core/commit/0a032e34189ac992d7574fc85b32a9c5d5c07ee4) for an example of how these changes might be implemented.

**Comment by viferga** [comment]
Respect to the second point, I have used C89 mostly because I was wondering MetaCall may work with cases like COBOL migrations. For very old computers, maybe this standard may be needed. I don't know if this restriction does pay off. I think it is too restrictive and makes the code much more uglier. Most runtime won't work anyway with that kind of old computers so it does not make sense to continue like that.

In the first point you are right, I have avoided `goto`s for no real reason, just a bad practice, and error handling is basically nonexistent.

This happens in the whole codebase. If you start refactoring the Python Loader, it can be a great advance. Later on we can start moving to the Core. Respect to the commit you listed, yes, that's the proper way of doing it, feel free to refactor.

The only thing I request to you is to validate that all tests work and pass AddressSanitizer and Valgrind to verify you do not create new memory leaks, specially in fail-path tests. We just have added new PR and Issue templates, and also you can check here how to enable Asan and Valgrind for testing: https://github.com/metacall/core/blob/develop/docs/README.md#63-debugging

**Comment by Encrylize** [comment]
Great! I'll get started on the refactor.

**Comment by viferga** [comment]
@Encrylize Are you going to continue with this or can I close the issue?

**Comment by Encrylize** [comment]
@viferga Let's just close it for now. :)
